VPSShop/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls'))
]

website/urls.py
from django.urls import path

from . import views

app_name = "shop"
urlpatterns = [
    path("", views.home, name="home"),
    path("login", views.login, name="login"),
    path("logout", views.logout, name="logout"),
    path("register", views.register, name="register"),
    path("home", views.home, name="home"),
    path("order", views.orderStep1, name="order"),
    path("order/VPSType", views.orderStep2, name="order2"),
    path("order/os", views.orderStep3, name="order3"),
    path("order/confirm", views.orderConfirm, name="orderConfirm"),
    path("createVPS/<str:id>",views.createVPS,name="createVPS"),
    path("renewVPS/<str:id>",views.renewVPS,name="renewVPS"),
    path("VPSList", views.VPSList, name="VPSList"),
    path("invoiceList", views.invoiceList, name="invoiceList"),
    path("VPSDetail/<int:id>", views.VPSDetail, name="VPSDetail"),
    path("VPSStatusChange/<int:id>", views.changeVPSStatus, name="VPSStatusChange"),
    path("VPSRenewForm/<int:id>",views.renewVPSConfirm, name="VPSRenew"),
    path("VPSRenewComplete", views.invoice_renewVPS, name="VPSRenewComplete"),
    path("VPSDelete/<int:id>",views.deleteVPS, name="VPSDelete"),
    path("invoiceDetail/<str:id>", views.invoiceDetail, name="invoiceDetail"),
    path("invoiceCancel/<str:id>", views.cancelPayment, name="cancelPayment")
    
]

website/forms.py
import re
from datetime import datetime
import random
from pytz import timezone
from django import forms
from .models import CustomUser, PaymentMethod


class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(
        attrs={'id': 'login_account', 'placeholder': 'Tài khoản'}))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'id': 'login_password', 'placeholder': 'Mật khẩu'}))

    def username_exists(self, username, password):
        return CustomUser.objects.filter(username=username, password=password).exists()

    def check(self):
        username = self.data['username']
        password = self.data['password']

        return self.username_exists(username=username, password=password)

    def getID(self):
        username = self.data['username']
        password = self.data['password']
        return CustomUser.objects.get(username=username, password=password).id


class RegisterForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(
        attrs={'id': 'register_account_input', 'placeholder': 'Tài khoản'}))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'id': 'register_password_input', 'placeholder': 'Mật khẩu'}))
    passwordConfirm = forms.CharField(widget=forms.PasswordInput(
        attrs={'id': 'register_password_input_repeat', 'placeholder': 'Mật khẩu'}))
    email = forms.EmailField(widget=forms.EmailInput(
        attrs={'id': 'register_email_input', 'placeholder': 'Email'}))
    phone = forms.CharField(widget=forms.TextInput(
        attrs={'id': 'register_phone_input', 'placeholder': 'Số điện thoại'}))

    def username_exists(self, username):
        return CustomUser.objects.filter(username=username).exists()

    def check(self):
        return self.getData()['code']

    def getData(self):
        username = self.data['username']
        password = self.data['password']
        passwordConfirm = self.data.get('passwordConfirm')
        email = self.data['email']
        phone = self.data['phone']
        if len(username) < 6 or len(username) > 20 or (not username.isalnum()) or (' ' in username) or username[0].isdigit():
            return {
                'code': 1
            }

        if len(password) < 6 or len(password) > 20:
            return {
                'code': 2
            }
        if password and passwordConfirm and password != passwordConfirm:
            return {
                'code': 3
            }
        if not re.match(r'^0[0-9]{9}$', phone):
            return {
                'code': 4
            }
        if self.username_exists(username):
            return {
                'code': 5
            }
        return {
            'code': 0,
            'data': {
                'username': username,
                'password': password,
                'phone': phone,
                'email': email
            }

        }


class RenewForm(forms.Form):
    type_invoice = forms.IntegerField(widget=forms.HiddenInput())
    type_VPS = forms.CharField(widget=forms.HiddenInput())
    plan = forms.CharField(widget=forms.HiddenInput())
    CPU = forms.IntegerField(widget=forms.HiddenInput())
    RAM = forms.IntegerField(widget=forms.HiddenInput())
    SSD = forms.IntegerField(widget=forms.HiddenInput())
    OS = forms.CharField(widget=forms.HiddenInput())
    price = forms.IntegerField(widget=forms.HiddenInput())
    paymentMethod = forms.IntegerField(widget=forms.HiddenInput())
    quantity = forms.IntegerField(widget=forms.NumberInput())
    time = forms.IntegerField(widget=forms.NumberInput())
    totalPrice = forms.IntegerField(widget=forms.HiddenInput())
    idUser = forms.IntegerField(widget=forms.HiddenInput())
    ipVPS = forms.CharField(widget=forms.HiddenInput())

    def getInvoiceData(self):
        hanoi = timezone('Asia/Saigon')
        current_time = datetime.now(hanoi)
        current_date = current_time.strftime("%Y%m%d")
        random_digits = ''.join([str(random.randint(0, 9)) for _ in range(6)])
        id = current_date + random_digits
        VPSType = self.data.get('plan')
        paymentMethod = PaymentMethod.objects.get(pk = self.data.get('paymentMethod')).name
        return {
            'id': id,
            'type': self.data.get('type_invoice'),
            'price': self.data.get('totalPrice'),
            'VPSType': VPSType,
            'status': 1,
            'paymentMethod': paymentMethod,
            'createAt': current_time,
            'finished': current_time,
            'id_user': self.data.get('idUser'),
            'targetVPS': self.data.get('ipVPS'),
            'quantity': self.data.get('quantity'),
            'time':self.data.get('time'),
            'OS': self.data.get('OS')
        }

class BaseNewVPSOrderForm(forms.Form):
    typeTemplate = forms.IntegerField(widget=forms.HiddenInput())
    type = forms.CharField(widget=forms.HiddenInput())
    OS = forms.IntegerField(widget=forms.HiddenInput())

    def getTypeTemplate(self):
        return self.data.get('typeTemplate')
    
    def getType(self):
        return self.data.get('type')
    
    def getOS(self):
        return self.data.get('OS')
    

website/views.py
from datetime import datetime
import random
from pytz import timezone
from dateutil.relativedelta import relativedelta
import string
from django.shortcuts import render, redirect
from .forms import LoginForm, RegisterForm, RenewForm, BaseNewVPSOrderForm
from .models import CustomUser, VPS, Invoice, PaymentMethod, VPSTypeTemplate, VPSTemplate, OSTemplate

active_user = None


class InvoiceTemp:
    def __init__(self, type_invoice, type_VPS, plan, CPU, RAM, SSD, OS, price, list_payment, id_user, ip_VPS=None) -> None:
        self.type_invoice = type_invoice
        self.type_VPS = type_VPS
        self.plan = plan
        self.CPU = CPU
        self.RAM = RAM
        self.SSD = SSD
        self.OS = OS.id
        self.OS_name = OS.name
        self.price = price
        self.list_payment = list_payment
        self.id_user = id_user
        self.ip_VPS = ip_VPS


def login(request):
    global active_user
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.check():
            active_user = form.getID()
            return redirect('/home')
        else:
            return render(request, 'login.html', {'form': LoginForm(), 'err_message': "Tài khoản hoặc mật khẩu không chính xác"})
    else:
        return render(request, 'login.html', {'form': LoginForm()})


def logout(request):
    global active_user
    active_user = None
    return redirect('/login')


def register(request):
    if request.method == 'POST':
        form = RegisterForm(data=request.POST)
        if form.check() == 0:
            data = form.getData()['data']
            create_user(data['username'], data['password'],
                        data['email'], data['phone'])
            return redirect('/login')
        else:

            return render(request, 'register.html', {
                'form': form, 'err_code': form.check()})
    else:
        return render(request, 'register.html', {'form': RegisterForm()})


def home(request):
    global active_user
    if active_user is not None:
        total_vps = VPS.objects.filter(id_user=active_user).count()
        total_running = VPS.objects.filter(
            id_user=active_user, status=1).count()
        total_invoice = Invoice.objects.filter(id_user=active_user).count()
        total_invoice_pending = Invoice.objects.filter(
            id_user=active_user, status=1).count()
        return render(request, 'home.html', {'sidebar_menu': 1, 'user': CustomUser.objects.get(pk=active_user).username, 'data': {
            "total_vps": total_vps,
            "total_running": total_running,
            "total_invoice": total_invoice,
            "total_invoice_pending": total_invoice_pending,
        }})
    else:
        return redirect('/login')


def orderStep1(request):
    global active_user
    if active_user is not None:
        vpsTypeTemp = VPSTypeTemplate.objects.all()
        form = BaseNewVPSOrderForm()
        return render(request, 'order.html', {'sidebar_menu': 2, 'user': CustomUser.objects.get(pk=active_user).username, 'vpsTypeTemp': vpsTypeTemp, 'form': form})
    else:
        return redirect('/login')


def orderStep2(request):
    global active_user
    if active_user is not None:
        form = BaseNewVPSOrderForm(request.POST)
        vpsType = VPSTemplate.objects.filter(type_id=form.getTypeTemplate())
        return render(request, 'order.html', {'sidebar_menu': 2, 'user': CustomUser.objects.get(pk=active_user).username, 'vpsType': vpsType, 'form': form})
    else:
        return redirect('/login')


def orderStep3(request):
    global active_user
    if active_user is not None:
        form = BaseNewVPSOrderForm(request.POST)
        OS = OSTemplate.objects.all()
        return render(request, 'order.html', {'sidebar_menu': 2, 'user': CustomUser.objects.get(pk=active_user).username, 'os': OS, 'form': form})
    else:
        return redirect('/login')


def orderConfirm(request):
    global active_user
    if active_user is not None:
        form = BaseNewVPSOrderForm(request.POST)
        plan = VPSTemplate.objects.get(pk=form.getType())
        paymentMethods = PaymentMethod.objects.all()
        data = InvoiceTemp(1, VPSTypeTemplate.objects.get(pk=form.getTypeTemplate()).name, plan.id, plan.CPU, plan.RAM,
                           plan.SSD, OSTemplate.objects.get(pk=form.getOS()), plan.pricePerMonth, paymentMethods, active_user)
        initial_data = {
            'type_invoice': data.type_invoice,
            'type_VPS': data.type_VPS,
            'plan': data.plan,
            'CPU': data.CPU,
            'RAM': data.RAM,
            'SSD': data.SSD,
            'OS': data.OS,
            'price': data.price,
            'quantity': 1,
            'time': 1,
            'paymentMethod': data.list_payment[0].id,
            'totalPrice': data.price,
            'idUser': data.id_user,
            'ipVPS': data.ip_VPS
        }
        form = RenewForm(initial=initial_data)
        return render(request, 'invoiceConfirm.html', {'sidebar_menu': 2, 'user': CustomUser.objects.get(pk=active_user).username, 'data': data, 'form': form})
    else:
        return redirect('/login')


def VPSList(request):
    global active_user
    if active_user is not None:
        return render(request, 'VPSList.html', {'sidebar_menu': 3, 'user': CustomUser.objects.get(pk=active_user).username, 'vpsList': VPS.objects.filter(id_user=active_user)})
    else:
        return redirect('/login')


def invoiceList(request):
    global active_user
    if active_user is not None:
        return render(request, 'invoiceList.html', {'sidebar_menu': 4, 'user': CustomUser.objects.get(pk=active_user).username, 'invoiceList': Invoice.objects.filter(id_user=active_user)})
    else:
        return redirect('/login')


def VPSDetail(request, id):
    global active_user
    if active_user is not None:
        data = VPS.objects.get(pk=id)
        return render(request, 'VPSDetail.html', {'sidebar_menu': 3, 'user': CustomUser.objects.get(pk=active_user).username, 'vps': data})
    else:
        return redirect('/login')


def invoiceDetail(request, id):
    global active_user
    if active_user is not None:
        data = Invoice.objects.get(pk=id)
        return render(request, 'invoiceDetail.html', {'sidebar_menu': 4, 'user': CustomUser.objects.get(pk=active_user).username, 'invoice': data})
    else:
        return redirect('/login')


def createVPS(request, id):
    global active_user
    if active_user is not None:
        invoice = Invoice.objects.get(pk=id)
        type = VPSTemplate.objects.get(pk=invoice.VPSType).type.id
        for i in range(invoice.quantity):
            new_ip = createIP(type)
            while not checkIP(new_ip):
                new_ip = createIP(type)
            VPSTemp = VPSTemplate.objects.get(pk=invoice.VPSType)
            hanoi = timezone('Asia/Saigon')
            expired_date = datetime.now(hanoi) + relativedelta(months=invoice.time)
            create_vps(new_ip, VPSTemp.type.id, VPSTemp.id, VPSTemp.CPU, VPSTemp.RAM, VPSTemp.SSD,
                       VPSTemp.pricePerMonth, expired_date, createUsername(), createPassword(), invoice.OS)
        invoice.status = 2
        invoice.save()
        return redirect('/VPSList')
    else:
        return redirect('/login')
    
def renewVPS(request, id):
    global active_user
    if active_user is not None:
        invoice = Invoice.objects.get(pk=id)
        vps = VPS.objects.get(ip=invoice.targetVPS)
        vps.expired_date+=relativedelta(months=invoice.time)
        vps.save()
        invoice.status = 2
        invoice.save()
        return redirect('/VPSDetail/' + str(vps.id))
    else:
        return redirect('/login')

def changeVPSStatus(request, id):
    vps = VPS.objects.get(pk=id)
    if (vps.status == 1):
        vps.status = 2
    else:
        vps.status = 1
    vps.save()
    return redirect('/VPSDetail/' + str(id))


def renewVPSConfirm(request, id):
    global active_user
    if active_user is not None:
        vps = VPS.objects.get(pk=id)
        paymentMethods = PaymentMethod.objects.all()
        data = InvoiceTemp(2, vps.type, vps.plan, vps.CPU, vps.RAM, vps.SSD, vps.OS,
                           vps.price, paymentMethods, active_user, vps.ip)
        initial_data = {
            'type_invoice': data.type_invoice,
            'type_VPS': data.type_VPS,
            'plan': data.plan,
            'CPU': data.CPU,
            'RAM': data.RAM,
            'SSD': data.SSD,
            'OS': data.OS,
            'price': data.price,
            'quantity': 1,
            'time': 1,
            'paymentMethod': data.list_payment[0].id,
            'totalPrice': data.price,
            'idUser': data.id_user,
            'ipVPS': data.ip_VPS
        }
        form = RenewForm(initial=initial_data)
        return render(request, 'invoiceConfirm.html', {'sidebar_menu': 2, 'user': CustomUser.objects.get(pk=active_user).username, 'data': data, 'form': form})
    else:
        return redirect('/login')


def invoice_renewVPS(request):
    global active_user
    if active_user is not None:
        form = RenewForm(data=request.POST)
        invoice = form.getInvoiceData()
        quantity = 1
        if(invoice['quantity']): quantity = invoice['quantity']
        create_invoice(invoice['id'], invoice['id_user'], invoice['type'], invoice['price'],
                       invoice['VPSType'], invoice['paymentMethod'], invoice['createAt'], invoice['finished'], quantity , invoice['time'], invoice['OS'], invoice['targetVPS'])
        data = Invoice.objects.get(pk=invoice['id'])
        return redirect('/invoiceDetail/' + str(data.id))
    else:
        return redirect('/login')

def cancelPayment(request, id):
    global active_user
    if active_user is not None:
        invoice = Invoice.objects.get(pk=id)
        invoice.status = 0
        invoice.save()
        return redirect('/invoiceDetail/' + id)
    else: 
        return redirect('/login')

def deleteVPS(request, id):

website/templates/VPSDetail.html
{%extends 'layout.html'%} {% load static %} {%block css%}
<link rel="stylesheet" href="{%static 'VPSDetail.css'%}" />
{%endblock%} {%block title%} Chi tiết VPS {%endblock%} {%block content%} {%if vps%}
<div class="VPSDetail_content">
  <div class="header">Thông tin chi tiết VPS</div>
  <div class="detail">
    <div class="row">
      <div class="name">VPS IP</div>
      <div class="value">{{vps.ip}}</div>
    </div>
    <div class="row">
      <div class="name">Trạng thái</div>
      <div class="value">
        {%if vps.status == 1%}
        <span class="green">RUNNING</span></div>
        {%endif%}
        {%if vps.status == 2%}
        <span class="red">STOPPED</span></div>
        {%endif%}
      </div>
      <div class="row">
        <div class="name">Thông số</div>
        <div class="value">{{vps.CPU}} core(s) CPU, {{vps.RAM}}GB RAM, {{vps.SSD}}GB SSD</div>
      </div>
      <div class="row">
        <div class="name">OS</div>
        <div class="value">{{vps.OS.name}}</div>
      </div>
      <div class="row">
        <div class="name">Tài khoản VPS mặc định</div>
        <div class="value">{{vps.username}}</div>
      </div>
      <div class="row">
        <div class="name">Mật khẩu VPS mặc định</div>
        <div class="value">{{vps.password}}</div>
      </div>
    </div>
    
  </div>
  <div class="action">
    {%if vps.status == 2%}
    <form action="{%url 'shop:VPSStatusChange' vps.id%}" method="post">
      {%csrf_token%}
      <button class="green">Khởi động VPS</button>
    </form>
    {%endif%}
    {%if vps.status == 1%}
    <form action="{%url 'shop:VPSStatusChange' vps.id%}" method="post">
      {%csrf_token%}
      <button class="red">Tắt VPS</button>
    </form>
    {%endif%}
    <form action="{%url 'shop:VPSRenew' vps.id%}" method="post">
      {%csrf_token%}
      <button class="orange" id="renew">Gia hạn VPS</button>
    </form>
    <form action="{%url 'shop:VPSDelete' vps.id%}" method="post">
      {%csrf_token%}
      <button class="red">Huỷ VPS</button>
    </form>
  </div>
</div>

{%endif%} {%endblock%}

website/templates/home.html
{%extends 'layout.html'%} {% load static %} {%block css%}
<link rel="stylesheet" href="{%static 'home.css'%}" />
{%endblock%} {%block title%} Dashboard {%endblock%} {%block content%}
{%if data%}
<div class="dashboard_summary_list">
  <div class="dashboard_card">
    <div class="name">Tổng số VPS</div>
    <div class="number">{{data.total_vps}}</div>
    <a href="{%url 'shop:VPSList'%}" class="details">
      <span style="color: #1a73e8">{{data.total_running}}</span> VPS đang hoạt động
    </a>
  </div>
  <div class="dashboard_card">
    <div class="name">Tổng số hoá đơn</div>
    <div class="number">{{data.total_invoice}}</div>
    <a href="{%url 'shop:invoiceList'%}" class="details">
      <span style="color: #fb8c00">{{data.total_invoice_pending}}</span> hoá đơn đang chờ thanh toán
    </a>
  </div>
</div>
{%endif%}
{%endblock%}

website/templates/invoiceDetail.html
{%extends 'layout.html'%} {% load static %} {%block css%}
<link rel="stylesheet" href="{%static 'invoiceDetail.css'%}" />
{%endblock%} {%block title%} Chi tiết hoá đơn {%endblock%} {%block content%}
{%if invoice%}
<div class="invoiceDetail_content">
  <div class="header">Thông tin chi tiết hoá đơn</div>
  <div class="detail">
    <div class="row">
      <div class="name">ID</div>
      <div class="value">{{invoice.id}}</div>
    </div>
    <div class="row">
      <div class="name">Loại hoá đơn</div>
      <div class="value">
        <span class="green">
          {%if invoice.type == 1%}CREATE{%endif%} {%if invoice.type == 2%}RENEW{%endif%}
        </span>
      </div>
    </div>
    <div class="row">
      <div class="name">Trạng thái</div>
      <div class="value">
        {%if invoice.status == 1%}
        <span class="blue">PENDING</span>
        {%endif%} {%if invoice.status == 0%}
        <span class="gray">CANCELED</span>
        {%endif%} {%if invoice.status == 2%}
        <span class="green">DONE</span>
        {%endif%}
      </div>
    </div>
    <div class="row">
      <div class="name">Loại VPS</div>
      <div class="value">{{invoice.VPSType}}</div>
    </div>
    <div class="row">
      <div class="name">Phương thức thanh toán</div>
      <div class="value">{{invoice.paymentMethod}}</div>
    </div>
    <div class="row">
      <div class="name">Tổng tiền</div>
      <div class="value">{{invoice.price}} VND</div>
    </div>
  </div>
  <div class="button_container">
    {%if invoice.status == 1%}
  <form action="{%url 'shop:cancelPayment' invoice.id%}" method="post">
    {%csrf_token%}
    <div class="button">
      <button class="red">Hủy thanh toán</button>
    </div>
  </form>
  {%if invoice.type == 1%}
  <form action="{%url 'shop:createVPS' invoice.id%}" method="post">
    {%csrf_token%}
    <div class="button">
      <button class="green">Xác nhận thanh toán</button>
    </div>
  </form>
  {%endif%} {%if invoice.type == 2%}
  <form action="{%url 'shop:renewVPS' invoice.id%}" method="post">
    {%csrf_token%}
    <div class="button">
      <button class="green">Xác nhận thanh toán</button>
    </div>
  </form>
  {%endif%}
  {%endif%} 
  </div>
</div>

  {%endif%}
  {%endblock%}

website/templates/layout.html
{%load static%}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{%static 'normarlize.css'%}" />
    <link rel="stylesheet" href="{%static 'layout.css'%}" />
    {%block css%} {%endblock%}
    <title>{%block title%} {%endblock%}</title>
  </head>
  <body>
    <div class="container">
      <div class="sidebar">
        <div class="sidebar_user">
          <img src="{% static 'assets/images/avatar.svg' %}" alt="" />
          <div class="name">
            Xin chào,
            <span style="font-weight: bold">{%if user%}{{user}}{%endif%}</span>
          </div>
        </div>
        <a
          href="{%url 'shop:home'%}"
          class="sidebar_item {%if sidebar_menu%}{% if sidebar_menu == 1 %}selected{% endif %}{% endif %}"
          id="dashboard"
          >Dashboard</a
        >
        <a
          href="{%url 'shop:order'%}"
          class="sidebar_item {%if sidebar_menu%}{% if sidebar_menu == 2 %}selected{% endif %}{% endif %}"
          id="Order"
          >Thuê VPS</a
        >
        <a
          href="{%url 'shop:VPSList'%}"
          class="sidebar_item {%if sidebar_menu%}{% if sidebar_menu == 3 %}selected{% endif %}{% endif %}"
          id="VPSList"
          >Danh sách VPS</a
        >
        <a
          href="{%url 'shop:invoiceList'%}"
          class="sidebar_item {%if sidebar_menu%}{% if sidebar_menu == 4 %}selected{% endif %}{% endif %}"
          id="invociesList"
          >Danh sách hoá đơn</a
        >
        <a href="{%url 'shop:logout'%}" class="sidebar_item" id="invociesList"
          >Đăng xuất</a
        >
      </div>
      <div class="content">{%block content%} {%endblock%}</div>
    </div>
  </body>
</html>

website/templates/order.html
{%extends 'layout.html'%} {% load static %} {%block css%}
<link rel="stylesheet" href="{%static 'order.css'%}" />
{%endblock%} {%block title%} Thuê VPS {%endblock%} {%block content%} {%if vpsTypeTemp%}
<form action="{%url 'shop:order2' %}" method="post">
  {%csrf_token%} {{form.typeTemplate}}

  <div class="order_step">
    <div class="header">Chọn loại server</div>
    <div class="VPSTypeList">
      {%for element in vpsTypeTemp%}
      <div class="VPSType" vpsTypeID="{{element.id}}">
        <div class="header">{{element.name}}</div>
        <div class="details">{{element.description}}</div>
      </div>
      {%endfor%}
    </div>
  </div>
  <div class="order_next">
    <button class="green">Tiếp tục</button>
  </div>
</form>
{%endif%} {%if vpsType%}
<form action="{%url 'shop:order3' %}" method="post">
  {%csrf_token%}{{form.typeTemplate}} {{form.type}}
  <div class="order_step">
    <div class="header">Chọn loại VPS</div>
    <div class="VPSList">
      {%for element in vpsType%}
      <div class="VPSPlan" plan-id="{{element.id}}">
        <div class="name">{{element.id}}</div>
        <div class="details">
          - <span>{{element.CPU}}</span> core(s) CPU <br />
          - <span>{{element.RAM}}</span> GB RAM <br />
          - <span>{{element.SSD}}</span> GB SSD <br />
        </div>
        <div class="price">{{element.pricePerMonth}} VND</div>
      </div>
      {%endfor%}
    </div>
  </div>
  <div class="order_next">
    <button class="green">Tiếp tục</button>
  </div>
</form>
{%endif%} {%if os%}
<form action="{%url 'shop:orderConfirm'%}" method="post">
  {%csrf_token%}{{form.typeTemplate}} {{form.type}}{{form.OS}}
  <div class="order_step">
    <div class="header">Chọn hệ điều hành</div>
    <div class="OSList">
      {%for element in os%}
      <div class="OS" os-id="{{element.id}}">{{element.name}}</div>
      {%endfor%}
    </div>
  </div>
  <div class="order_next">
    <button class="green">Tiếp tục</button>
  </div>
</form>
{%endif%}

<script>
  document.addEventListener("DOMContentLoaded", function () {
    var step1 = document.getElementsByClassName("VPSTypeList");
    var step2 = document.getElementsByClassName("VPSList");
    var step3 = document.getElementsByClassName("OSList");
    if (step1) {
      var vpsTypes = document.querySelectorAll(".VPSType");
      vpsTypes.forEach(function (vpsType) {
        vpsType.addEventListener("click", function () {
          var vpsTypes = document.querySelectorAll(".VPSType");
          vpsTypes.forEach(function (vpsType) {
            vpsType.classList.remove("selected");
          });
          vpsType.classList.add("selected");
          var vpsTypeID = vpsType.getAttribute("vpsTypeID");
          document.getElementById("id_typeTemplate").value = vpsTypeID;
        });
      });
    }
    if (step2) {
      var vpsTypes = document.querySelectorAll(".VPSPlan");
      vpsTypes.forEach(function (vpsType) {
        vpsType.addEventListener("click", function () {
          var vpsTypes = document.querySelectorAll(".VPSPlan");
          vpsTypes.forEach(function (vpsType) {
            vpsType.classList.remove("selected");
          });
          vpsType.classList.add("selected");
          var vpsTypeID = vpsType.getAttribute("plan-id");
          document.getElementById("id_type").value = vpsTypeID;
        });
      });
    }
    if (step3) {
      var vpsTypes = document.querySelectorAll(".OS");
      vpsTypes.forEach(function (vpsType) {
        vpsType.addEventListener("click", function () {
          var vpsTypes = document.querySelectorAll(".OS");
          vpsTypes.forEach(function (vpsType) {
            vpsType.classList.remove("selected");
          });
          vpsType.classList.add("selected");
          var vpsTypeID = vpsType.getAttribute("os-id");
          document.getElementById("id_OS").value = vpsTypeID;
        });
      });
    }
  });
</script>
{%endblock%}